#!/usr/bin/env node
/**
 * Draws the element marks — fire, earth, water, air — as standalone SVG icons.
 *
 * The marks themselves are data: one path per element in data/arcana.json, and
 * how to draw one is in data/components.json under marks.element. Neither of
 * those is a picture, so this tool makes the pictures: one icon per element for
 * the book and the art docs to point at, plus one reference sheet showing the
 * set together.
 *
 * That is the whole reason the path lives in the data rather than in a drawing.
 * A card, a chit, a chapter of the rulebook and the explorer all say "fire" the
 * same way, because there is one fire mark and everything traces it.
 *
 * Each icon carries the two-plate contract like everything else the repository
 * generates (docs/art/01-two-plate-system.md): #wash is the element's ink as a
 * flat disc, #ink is the mark in soot alone, #grime is empty — an 18mm chit has
 * no room to be dirty. Delete the wash and the icon still reads, which is the
 * test docs/art/04-iconography.md sets for every mark in the set.
 *
 * Usage: node tools/build-icons.mjs [--check]
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readPalette, inkHex } from './lib/palette.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'docs', 'art', 'icons');
const checkOnly = process.argv.includes('--check');

const arcana = JSON.parse(readFileSync(join(ROOT, 'data/arcana.json'), 'utf8'));
const components = JSON.parse(readFileSync(join(ROOT, 'data/components.json'), 'utf8'));
const palette = readPalette(ROOT);

const SOOT = palette.ink.soot.hex;
const TALLOW = palette.paper.tallow.hex;

/** "oxide" -> the named ink; "soot-tint-40" -> that tint. One resolver, in
    tools/lib/palette.mjs, because tools/draw-item.mjs needs the same one. */
const ink = (name) => inkHex(name, palette);

const spec = components.marks.element;
const num = (n) => Number(n.toFixed(2));

/**
 * One element mark, drawn into a box of `size` at `x`,`y`, as {wash, ink}.
 *
 * The mark is authored on a 24-grid, so it is scaled rather than redrawn — and
 * the stroke is scaled with it, because a mark whose weight drifts with its size
 * is two marks.
 */
function markGroup(element, x, y, size, { disc = true } = {}) {
  /* Inside a disc the mark is pulled in about its own centre, or the ends of
     its ground line cross the ring - see components.json marks.element.onCard. */
  const inset = disc ? spec.onCard.insetInDisc : 1;
  const k = (size / 24) * inset;
  const cx = x + size / 2;
  const cy = y + size / 2;
  const at = `translate(${num(cx - 12 * k)} ${num(cy - 12 * k)}) scale(${num(k)})`;
  const r = 11.4 * (size / 24);
  return {
    wash: disc
      ? `<circle cx="${num(cx)}" cy="${num(cy)}" r="${num(r)}" fill="${ink(element.ink)}" opacity="${spec.onCard.washOpacity}"/>`
      : '',
    ink:
      (disc ? `<circle cx="${num(cx)}" cy="${num(cy)}" r="${num(r)}" fill="none" stroke="${SOOT}" stroke-width="${num(1.5 * (size / 24))}"/>` : '') +
      `<g transform="${at}" fill="${spec.fill}" stroke="${SOOT}" stroke-width="${spec.strokeWidth}" ` +
      `stroke-linecap="${spec.strokeLinecap}" stroke-linejoin="${spec.strokeLinejoin}">` +
      `<path d="${element.mark}"/></g>`,
  };
}

/** The layer skeleton every generated SVG in this repository shares. */
function plates({ w, h, title, desc, wash, ink, grime = '' }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">
<title>${title}</title>
<desc>${desc} Generated by tools/build-icons.mjs from data/arcana.json and data/components.json - do not edit. The ink plate alone is the black-and-white edition.</desc>
<g id="wash">
  <rect x="0" y="0" width="${w}" height="${h}" fill="${TALLOW}"/>
  ${wash}
</g>
<g id="ink">
  ${ink}
</g>
<g id="grime"></g>
</svg>
`;
}

/* ------------------------------------------------------------ one per element */

const SIZE = 64;            // drawn square; the SVG scales to whatever uses it
const PAD = 6;

const wanted = new Map();

for (const e of arcana.elements) {
  const g = markGroup(e, PAD, PAD, SIZE - 2 * PAD);
  wanted.set(
    `element-${e.id}.svg`,
    plates({
      w: SIZE, h: SIZE,
      title: `${e.name} — the element mark`,
      desc: `${e.markNote} ${e.summary}`,
      wash: g.wash, ink: g.ink,
    })
  );
}

/* --------------------------------------------------------- the reference sheet */

const CELL = 84, LABEL = 22;
const sheetW = CELL * arcana.elements.length;
const sheetH = CELL + LABEL;
const cells = arcana.elements.map((e, i) => {
  const g = markGroup(e, i * CELL + 12, 12, CELL - 24);
  return {
    wash: g.wash,
    ink:
      g.ink +
      `<text x="${i * CELL + CELL / 2}" y="${CELL + 12}" font-size="11" text-anchor="middle" letter-spacing="1.6" ` +
      `font-family="Helvetica, Arial, sans-serif" fill="${SOOT}">${e.name.toUpperCase()}</text>`,
  };
});

wanted.set(
  'elements.svg',
  plates({
    w: sheetW, h: sheetH,
    title: 'The four element marks',
    desc: 'Fire, earth, water and air, drawn on one construction: a ground line and what the element does to it.',
    wash: cells.map((c) => c.wash).join('\n  '),
    ink: cells.map((c) => c.ink).join('\n  '),
  })
);

wanted.set(
  'README.md',
  `# Generated icons

Do not edit anything in this folder. Every file here is written by
\`tools/build-icons.mjs\` from \`data/arcana.json\` (the mark paths) and
\`data/components.json\` (how to draw one). Change a mark there and re-run:

\`\`\`bash
node tools/build-icons.mjs
\`\`\`

| File | What it is |
| --- | --- |
${arcana.elements.map((e) => `| [\`element-${e.id}.svg\`](element-${e.id}.svg) | ${e.name} — ${e.markNote.toLowerCase().replace(/\.$/, '')} |`).join('\n')}
| [\`elements.svg\`](elements.svg) | All four together, for the art docs and the rulebook |

The marks are stroked, never filled, on a 24-unit grid, and each one is built on
the same construction: a ground line, and what the element does to it. They are
deliberately **not** the alchemical triangles —
[\`../04-iconography.md\`](../04-iconography.md) bans borrowed real-world symbols
along with letterforms, and the triangles are the most borrowed symbols there are.

Both plates are present in every file, so \`remove(#wash)\` gives the
black-and-white edition and \`tools/validate-art.mjs\` can check them like any
other generated art.
`
);

/* ------------------------------------------------------------------ output */

if (checkOnly) {
  let stale = false;
  for (const [name, content] of wanted) {
    let current = '';
    try { current = readFileSync(join(OUT_DIR, name), 'utf8'); } catch { /* absent is stale */ }
    if (current !== content) { console.error(`docs/art/icons/${name} is stale.`); stale = true; }
  }
  if (existsSync(OUT_DIR)) {
    for (const f of readdirSync(OUT_DIR)) {
      if (!wanted.has(f)) { console.error(`docs/art/icons/${f} is no longer generated.`); stale = true; }
    }
  }
  if (stale) { console.error('Run: node tools/build-icons.mjs'); process.exit(1); }
  console.log(`docs/art/icons/ is up to date (${arcana.elements.length} element marks)`);
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  for (const f of readdirSync(OUT_DIR)) if (!wanted.has(f)) unlinkSync(join(OUT_DIR, f));
  for (const [name, content] of wanted) writeFileSync(join(OUT_DIR, name), content, 'utf8');
  console.log(`wrote ${wanted.size} files to docs/art/icons/ — ${arcana.elements.map((e) => e.id).join(', ')}`);
}
