#!/usr/bin/env node
/**
 * Renders the mint — the setup guide, the pipeline and the live queue — into one
 * printable HTML page at docs/mint/index.html.
 *
 * Why a page at all: GitHub Pages serves markdown as plain text, so on the
 * published site MINT-SETUP.md is a wall of unformatted characters. The whole
 * point of that document is that somebody follows it while running a mint, and
 * a document you cannot read on the site is a document nobody reads.
 *
 * Three sources, in the order you need them:
 *
 *   docs/MINT-SETUP.md      how to set the two agents up and what to paste
 *   docs/MINT.md            what the pipeline is - the lines, steps, contracts
 *   docs/art/mint/QUEUE.md  who owes what right now, generated by mint-queue.mjs
 *
 * Committed, like docs/book/index.html and docs/data/bundle.js, because Pages
 * serves the files in the branch. Run mint-queue.mjs BEFORE this one: the queue
 * is this page's third section, so a stale queue is a stale page.
 *
 * Usage: node tools/build-mint.mjs [--check]
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderMarkdown, docPage } from './lib/docpage.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DOCS = join(ROOT, 'docs');
const OUT_DIR = join(DOCS, 'mint');
const OUT = join(OUT_DIR, 'index.html');
const checkOnly = process.argv.includes('--check');

const palette = JSON.parse(readFileSync(join(DOCS, 'art/palette.json'), 'utf8'));

/* The page's sections. `path` is relative to docs/, which is also what every
   link inside these files is relative to - that is what makes the rewriting
   below one line of arithmetic rather than a table of special cases. */
const SOURCES = [
  { id: 's-setup', path: 'MINT-SETUP.md' },
  { id: 's-mint', path: 'MINT.md' },
  { id: 's-queue', path: 'art/mint/QUEUE.md' },
];

const idByPath = new Map(SOURCES.map((s) => [s.path, s.id]));

/**
 * A link written relative to its own document, rewritten to work from
 * docs/mint/index.html - and turned into an anchor if it points at one of the
 * other two sections, because they are on this page rather than beside it.
 */
function rewriterFor(sourcePath) {
  const base = posix.dirname(sourcePath);
  return (href) => {
    if (/^(https?:|mailto:|#)/.test(href)) return href;
    const [target, hash = ''] = href.split('#');
    if (!target) return href;
    const resolved = posix.normalize(posix.join(base, target));
    const section = idByPath.get(resolved);
    if (section) return `#${section}`;
    /* Everything else is still a file in the repository: docs/mint/ is one level
       down from docs/, so a path relative to docs/ needs one ../ in front. */
    return `../${resolved}${hash ? '#' + hash : ''}`;
  };
}

const sections = SOURCES.map((s) => ({
  id: s.id,
  ...renderMarkdown(readFileSync(join(DOCS, s.path), 'utf8'), {
    rewriteHref: rewriterFor(s.path),
    fallbackTitle: s.path,
  }),
}));

const page = docPage({
  palette,
  pageTitle: 'game1 — the mint',
  barTitle: 'game1 — the mint',
  barLinks: [
    { href: '../index.html', label: 'Explorer' },
    { href: '../book/index.html', label: 'The rulebook' },
    { href: '../cards/index.html', label: 'Card fronts' },
    { href: '../map/index.html', label: 'Map' },
  ],
  printLabel: 'Print the guide',
  sections,
});

if (checkOnly) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* absent counts as stale */ }
  if (current !== page) {
    console.error('docs/mint/index.html is stale. Run: node tools/mint-queue.mjs && node tools/build-mint.mjs');
    process.exit(1);
  }
  console.log('docs/mint/index.html is up to date');
} else {
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(OUT, page, 'utf8');
  console.log(
    `wrote docs/mint/index.html (${(page.length / 1024).toFixed(1)} kB) from ${SOURCES.map((s) => s.path).join(', ')}`
  );
}
