#!/usr/bin/env node
/**
 * Generates docs/design/14-annex.md — the printed rulebook's reference tables —
 * from data/*.json.
 *
 * The annex used to be the part of the rulebook most likely to lie: long lists
 * transcribed by hand from the data, one rename away from being wrong. So it is
 * generated, like docs/data/bundle.js, and committed: edit the data, run this,
 * commit both. Everything here is a TABLE on purpose — the annex is the part of
 * the book you scan with a finger, not the part you read.
 *
 * Usage: node tools/build-annex.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(ROOT, 'data');
const OUT = join(ROOT, 'docs', 'design', '14-annex.md');
const checkOnly = process.argv.includes('--check');

const read = (f) => JSON.parse(readFileSync(join(DATA, f), 'utf8'));
const terrain = read('terrain.json');
const travel = read('travel.json');
const discovery = read('discovery.json');
const commodities = read('commodities.json');
const tools = read('tools.json');
const buildings = read('buildings.json');
const rules = read('rules.json');
const peoples = read('peoples.json');
const items = read('items.json');
const events = read('events.json');
const transport = read('transport.json');
const monsters = read('monsters.json');
const vehicles = read('vehicles.json');
const characters = read('characters.json');
const quests = read('quests.json');
const arcana = read('arcana.json');
const modifications = read('modifications.json');

const lines = [];
const say = (s = '') => lines.push(s);

/** One markdown table. Cells are stringified and pipes escaped. */
function table(headers, rows) {
  const cell = (v) => String(v ?? '—').replace(/\|/g, '\\|');
  say(`| ${headers.map(cell).join(' | ')} |`);
  say(`| ${headers.map(() => '---').join(' | ')} |`);
  for (const row of rows) say(`| ${row.map(cell).join(' | ')} |`);
  say();
}

const list = (arr) => (arr && arr.length ? arr.join(', ') : '—');

/**
 * An element, with its mark.
 *
 * The mark comes from docs/art/icons/, which tools/build-icons.mjs draws from
 * the same data/arcana.json this file is reading - so a table in the printed
 * annex says fire with the mark a card says it with. The path is relative to
 * docs/design/, which is also where docs/book/ sits, so it resolves in the
 * rendered book, on GitHub, and in a plain markdown reader alike.
 */
const elementMark = (id) => `![](../art/icons/element-${id}.svg)`;
const element = (id) => `${elementMark(id)} ${id}`;
const io = (arr) => (arr && arr.length ? arr.map((i) => `${i.qty} ${i.commodity}`).join(' + ') : '—');

say('# 14 — Annex: the reference tables');
say();
say('> **Generated by `tools/build-annex.mjs` — do not edit by hand.** Edit the data');
say('> in `data/*.json`, run the tool, and commit both. Every number here is the same');
say('> number the explorer and the simulator read.');
say();

/* ------------------------------------------------------------------ terrain */
say('## Terrain');
say();
say('The letter code is printed in the bottom corner of every hex on every map.');
say('It is the ruling when the artwork straddles a grid line, and it keys the');
say('travel and discovery tables below.');
say();
table(
  ['Code', 'Terrain', 'Move', 'Road ×', 'Rail ×', 'Features', 'Deposits'],
  terrain.terrains.map((t) => [
    `**${t.code}**`, t.name, t.moveCost === 99 ? 'boat' : t.moveCost,
    t.roadCostMultiplier || '—', t.railCostMultiplier || '—',
    list(t.features), list(t.deposits),
  ])
);

/* ------------------------------------------------------------------- travel */
say('## Travel speeds — hexes per day leg');
say();
const codes = travel.terrainCodes;
table(
  ['Mode', ...codes.map((c) => `**${c}**`)],
  travel.speeds.modes.map((m) => [m.name, ...codes.map((c) => m.hexesPerDayLeg[c] || '—')])
);
say('Overrides: ' + travel.speeds.overrides.map((o) =>
  `**${o.name}** — ${Object.entries(o.hexesPerDayLeg).map(([m, v]) => `${m} ${v}`).join(', ')}`).join('; ') + '.');
say();
say('## Night legs');
say();
table(
  ['Light', 'Night speed'],
  [
    ['None', 'No travel at all, even on a road'],
    ['Torch', '1 hex (2 on a road); spends one use'],
    ['Lantern', 'Half day speed, rounded up'],
    ['Owl’s Eye potion', 'As a lantern, for one round'],
  ]
);
say('A night leg triggers a second discovery roll with the monster band widened by 1.');
say('Trains run at night at full speed with a lantern fitted; ships sail at half speed with one rigged.');
say('Caves can only be entered with a lit torch or lantern.');
say();

/* ---------------------------------------------------------------- discovery */
say('## Discovery tables — d20, roll where the leg ends');
say();
say('One roll per movement leg, on the table for the hex you **stopped** in. A road');
say('or rail on the hex overrides its terrain. Persistent results are marked on the');
say('hex with a tile or figure.');
say();
table(
  ['Table', 'Bands'],
  discovery.tables.map((t) => [
    t.name,
    t.entries.map((e) => `${e.roll} ${e.result}`).join(' · '),
  ])
);
say('Monster element weights by table:');
say();
table(
  ['Table', 'Fire', 'Earth', 'Water', 'Air'],
  discovery.tables.map((t) => [
    t.name,
    t.elementWeights?.fire ?? 0, t.elementWeights?.earth ?? 0,
    t.elementWeights?.water ?? 0, t.elementWeights?.air ?? 0,
  ])
);

/* -------------------------------------------------------------- commodities */
say('## Commodities');
say();
table(
  ['Commodity', 'Category', 'Bulk', 'Value', 'Perishes', 'Tags'],
  commodities.commodities.map((c) => [
    c.name, c.category, c.bulk, c.baseValue,
    c.perishRounds ? `${c.perishRounds} rounds` : '—', list(c.tags),
  ])
);

/* -------------------------------------------------------------------- tools */
say('## Tools');
say();
table(
  ['Tool', 'Made at', 'Craft', 'Hours', 'Value', 'Durability'],
  tools.tools.map((t) => [
    t.name, t.madeAt, io(t.craft?.inputs), t.craft?.effortHours, t.baseValue,
    t.baseDurability + (t.optional ? ' (optional)' : ''),
  ])
);

/* ---------------------------------------------------------------- buildings */
say('## Buildings');
say();
table(
  ['Building', 'Category', 'Tier', 'Cost', 'Points', 'Terrain'],
  buildings.buildings.map((b) => [
    b.name, b.category, b.tier, io(b.cost), b.buildPoints, list(b.terrain),
  ])
);

/* ------------------------------------------------------------------ peoples */
say('## Peoples');
say();
table(
  ['People', 'Die', 'Workers', 'Terrain comfort', 'Strength', 'Defence', 'Carries', 'Mana'],
  peoples.peoples.map((p) => [
    p.name, p.effortDie, p.startingWorkers, list(p.terrainComfort),
    p.strength?.base,
    p.defence?.base,
    `${(p.strength?.base ?? 0) * rules.carrying.kgPerStrength} kg`,
    p.manaStorage?.innate ? `${p.manaStorage.innate} innate` : 'talisman only',
  ])
);
say();
say('Carrying is not a separate number and has not been since strength swallowed');
say(`burden: a figure lifts strength × ${rules.carrying.kgPerStrength} ${rules.carrying.unit}, and the column above is that`);
say('sum rather than a value anybody chose.');
say('### Traits');
say();
table(
  ['People', 'Trait', 'Effect'],
  peoples.peoples.flatMap((p) => p.traits.map((t) => [p.name, t.name, t.effect]))
);
say('### Professions');
say();
table(
  ['Profession', 'Trained at', 'Coin', 'Hours', 'Bonus'],
  peoples.professions.map((p) => [
    p.name, p.building, p.trainCost?.coin, p.trainCost?.effortHours, p.bonus,
  ])
);

/* -------------------------------------------------------------------- items */
say('## Items');
say();
say('Mass is what the thing weighs. It counts against what the carrier can lift —');
say(`strength × ${rules.carrying.kgPerStrength} ${rules.carrying.unit}, printed on every character card — and it is not`);
say('bulk: bulk is a commodity\'s storage and shipping cost, and no item has one.');
say();
say(`No figure in the game shoulders more than ${Math.max(...peoples.peoples.map((p) => (p.strength?.base ?? 0) * rules.carrying.kgPerStrength), ...characters.characters.map((c) => c.strength * rules.carrying.kgPerStrength))} ${rules.carrying.unit} unaided, and`);
say('nothing walks a token for it: a load either fits under the printed limit or');
say('it does not.');
say();
for (const cls of items.classes) {
  const rows = items.items.filter((i) => i.class === cls.id);
  if (!rows.length) continue;
  say(`### ${cls.name}`);
  say();
  const extra = cls.id === 'talisman' ? ['Capacity'] : [];
  table(
    ['Item', 'Made at', 'Inputs', 'Hours', 'Value', 'Mass', ...extra, 'Effects'],
    rows.map((i) => [
      i.name + (i.cardCode ? ` (${i.cardCode})` : ''), i.madeAt, io(i.inputs), i.effortHours, i.baseValue,
      `${i.massKg} kg`,
      ...(cls.id === 'talisman' ? [i.manaCapacity] : []),
      (i.effects || []).join(' '),
    ])
  );
}

/* ---------------------------------------------------------------- transport */
say('## Transport modes');
say();
table(
  ['Mode', 'Tier', 'Capacity', 'Speed', 'Needs', 'Buy', 'Upkeep', 'Theft risk'],
  transport.modes.map((m) => [
    m.name, m.tier, m.capacity,
    m.speedOnRoad ? `${m.speed} (${m.speedOnRoad} on road)` : m.speed,
    m.requires === 'none' ? '—' : m.requires, m.buyCost || 'free', m.upkeep, '★'.repeat(m.theftRisk || 0) || '—',
  ])
);

/* ----------------------------------------------------------------- vehicles */
say('## Vehicle deck');
say();
say('**H** is the hull, **C** the bulk of its hold — the two boxes of a vehicle');
say('card\'s summary strip. A vehicle in play is dealt a player board of its own and');
say('run like a player who is not a person: the hull walks that board\'s health');
say('track, and the cargo and modifications lie in its four kit slots.');
say();
table(
  ['Code', 'Vehicle', 'Kind', 'Cargo', 'Hull', 'Quirk'],
  vehicles.vehicles.map((v) => [
    v.cardCode, v.name, v.mode, v.cargoCapacity, v.hull, v.quirk,
  ])
);

/* ----------------------------------------------------------------- monsters */
say('## Monster deck');
say();
say('S = slay (always allowed), E = enslave, B = befriend, D = domesticate.');
say('Slaying yields the mana; the other three trade mana away for a living asset.');
say();
table(
  ['Code', 'Monster', 'Element', 'Str', 'Def', 'Health', 'Mana', 'Ground', 'Options'],
  monsters.monsters.map((m) => [
    m.cardCode, m.name + (m.unique ? ' *(unique)*' : ''), element(m.element), m.strength, m.defence, m.health, m.manaYield,
    list(m.terrains),
    'S' + (m.options.enslave ? ' E' : '') + (m.options.befriend ? ' B' : '') + (m.options.domesticate ? ' D' : ''),
  ])
);
say();
say(`In a fight: ${rules.conflict.attack.rule} ${rules.conflict.attack.formula}, clamped to`);
say(`${rules.conflict.attack.clamp[0]}+ and ${rules.conflict.attack.clamp[1]}+. Strength is what a thing swings with, defence is what makes`);
say('you miss — a stone boar barely swings and still turns a sword.');

/* --------------------------------------------------------------- characters */
say('## Character deck');
say();
say('The six boxes of the summary strip across the top of every character card,');
say('in the order they are printed in — and the same letters the player board');
say('calls its tracks, so setting up is reading across the strip and placing');
say('tokens left to right.');
say();
table(
  ['Code', 'Character', 'People', 'Calling', 'H', 'S', 'D', 'M', rules.currency.symbol, 'KG', 'Traits'],
  characters.characters.map((c) => [
    c.cardCode, c.name, c.people, c.calling,
    c.health, c.strength, c.defence, c.manaCapacity || '—', c.startingGold,
    c.strength * rules.carrying.kgPerStrength,
    (c.traits || []).join(' '),
  ])
);

/* ------------------------------------------------------------------- quests */
say('## Quest deck');
say();
table(
  ['Code', 'Quest', 'Type', 'Cx', 'Task'],
  quests.quests.map((q) => [
    q.cardCode, q.name, q.type, q.complexity,
    q.task || `${q.stages.length} stages: ${q.stages.map((s) => s.name).join(' → ')}`,
  ])
);

/* ------------------------------------------------------ elements and arcana */
say('## The elements');
say();
say('Four elements, four marks. The mark is data - one path per element in');
say('`data/arcana.json` - so a card, a chit, this table and the explorer all say');
say('fire the same way. `tools/build-icons.mjs` draws them.');
say();
table(
  ['Mark', 'Element', 'Ink', 'At home'],
  arcana.elements.map((e) => [elementMark(e.id), `**${e.name}**`, e.ink, e.summary])
);

say('## Spells');
say();
table(
  ['Code', 'Spell', 'Element', 'Mana', 'Effect'],
  arcana.spells.map((s) => [s.cardCode, s.name, element(s.element), s.cost, s.effect])
);

say('## Enchantments');
say();
say(arcana.enchantments.$comment.split('.')[0] + '.');
say();
table(
  ['Code', 'Enchantment', 'Element', 'Mana', 'Bound to', 'Effect'],
  arcana.enchantments.cards.map((e) => [e.cardCode, e.name, element(e.element), e.cost, e.boundTo, e.effect])
);

/* ----------------------------------------------------------- modifications */
say('## Modification deck');
say();
say('Fittings and enchantments bolted onto a vehicle. They share the vehicle\'s');
say(`slots — ${modifications.slots.base} on most, and at most ${modifications.slots.enchantmentLimit} enchantment whatever the count — so a`);
say('shipwright and a hedge-witch are competing for the same hull.');
say();
table(
  ['Code', 'Modification', 'Class', 'Fits', 'Cost', 'Effect'],
  modifications.modifications.map((m) => [
    m.cardCode, m.name, m.class, list(m.fits),
    m.manaCost ? `${m.manaCost} ${m.element} mana` : io(m.inputs),
    m.effect,
  ])
);

/* -------------------------------------------------------------------- events */
say('## Event deck');
say();
table(
  ['Card', 'Category', 'Scope', 'Copies'],
  events.cards.map((c) => [c.name, c.category, c.scope, c.copies])
);
say(`${events.deck.totalCards} cards. ${events.deck.when}`);
say();

const out = lines.join('\n');
if (checkOnly) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* absent counts as stale */ }
  if (current !== out) {
    console.error('docs/design/14-annex.md is stale. Run: node tools/build-annex.mjs');
    process.exit(1);
  }
  console.log('docs/design/14-annex.md is up to date');
} else {
  writeFileSync(OUT, out, 'utf8');
  console.log(`wrote docs/design/14-annex.md (${(out.length / 1024).toFixed(1)} kB)`);
}
