#!/usr/bin/env node
/**
 * Generates docs/design/14-annex.md — the printed rulebook's reference tables —
 * from data/*.json.
 *
 * The annex used to be the part of the rulebook most likely to lie: long lists
 * transcribed by hand from the data, one rename away from being wrong. So it is
 * generated, like docs/data/bundle.js, and committed: edit the data, run this,
 * commit both. Everything here is a TABLE on purpose — the annex is the part of
 * the book you scan with a finger, not the part you read.
 *
 * Usage: node tools/build-annex.mjs [--check]
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DATA = join(ROOT, 'data');
const OUT = join(ROOT, 'docs', 'design', '14-annex.md');
const checkOnly = process.argv.includes('--check');

const read = (f) => JSON.parse(readFileSync(join(DATA, f), 'utf8'));
const terrain = read('terrain.json');
const travel = read('travel.json');
const discovery = read('discovery.json');
const commodities = read('commodities.json');
const tools = read('tools.json');
const buildings = read('buildings.json');
const rules = read('rules.json');
const peoples = read('peoples.json');
const items = read('items.json');
const events = read('events.json');
const transport = read('transport.json');
const monsters = read('monsters.json');
const vehicles = read('vehicles.json');
const characters = read('characters.json');
const quests = read('quests.json');
const arcana = read('arcana.json');
const modifications = read('modifications.json');
const pricing = read('pricing.json');

const lines = [];
const say = (s = '') => lines.push(s);

/** One markdown table. Cells are stringified and pipes escaped. */
function table(headers, rows) {
  const cell = (v) => String(v ?? '—').replace(/\|/g, '\\|');
  say(`| ${headers.map(cell).join(' | ')} |`);
  say(`| ${headers.map(() => '---').join(' | ')} |`);
  for (const row of rows) say(`| ${row.map(cell).join(' | ')} |`);
  say();
}

const list = (arr) => (arr && arr.length ? arr.join(', ') : '—');

/**
 * An element, with its mark.
 *
 * The mark comes from docs/art/icons/, which tools/build-icons.mjs draws from
 * the same data/arcana.json this file is reading - so a table in the printed
 * annex says fire with the mark a card says it with. The path is relative to
 * docs/design/, which is also where docs/book/ sits, so it resolves in the
 * rendered book, on GitHub, and in a plain markdown reader alike.
 */
const elementMark = (id) => `![](../art/icons/element-${id}.svg)`;
/* The same bargain for the three market-memory marks: one set of paths in
   data/pricing.json, drawn once by tools/build-icons.mjs, and the annex says
   "glut" with the mark that is engraved on the token. */
const pricingMark = (id) => `![](../art/icons/pricing-${id}.svg)`;
const priceModel = (id) => {
  const m = pricing.models.find((x) => x.id === id);
  return m ? `${pricingMark(m.id)} ${m.name}` : '—';
};
const element = (id) => `${elementMark(id)} ${id}`;
const io = (arr) => (arr && arr.length ? arr.map((i) => `${i.qty} ${i.commodity}`).join(' + ') : '—');

say('# 14 — Annex: the reference tables');
say();
say('> **Generated by `tools/build-annex.mjs` — do not edit by hand.** Edit the data');
say('> in `data/*.json`, run the tool, and commit both. Every number here is the same');
say('> number the explorer and the simulator read.');
say();

/* ---------------------------------------------------------------- the web */
/* The one picture in the annex: the dependency graph, drawn by
   tools/build-graph.mjs from the same cross-file references the validator
   checks. Referenced by path, so a rebuilt graph reaches the book with no
   edit here - same bargain as the element marks below. */
say('## The web of things');
say();
say('Before the tables, the shape of them: every thing in the game and every');
say('arrow between them, computed from the same cross-file references');
say('`tools/validate-data.mjs` checks — so this picture cannot know a tie the');
say('validator does not enforce. An arrow points from the thing whose data');
say('names the other, at the thing it names: a job points at the ore it takes');
say('in, the iron it puts out and the smelter it runs in alike. The explorer’s');
say('**Graph** tab is this same drawing, live — pan it, drag it, click any dot');
say('for its entry.');
say();
say('![The dependency graph: every thing in the game, and every reference between them](../art/graph/dependencies.svg)');
say();

/* ------------------------------------------------------------------ terrain */
say('## Terrain');
say();
say('The letter code is printed in the bottom corner of every hex on every map.');
say('It is the ruling when the artwork straddles a grid line, and it keys the');
say('travel and discovery tables below.');
say();
table(
  ['Code', 'Terrain', 'Move', 'Road ×', 'Rail ×', 'Features', 'Deposits'],
  terrain.terrains.map((t) => [
    `**${t.code}**`, t.name, t.moveCost === 99 ? 'boat' : t.moveCost,
    t.roadCostMultiplier || '—', t.railCostMultiplier || '—',
    list(t.features), list(t.deposits),
  ])
);

/* ------------------------------------------------------------------- travel */
say('## Travel speeds — hexes per day leg');
say();
const codes = travel.terrainCodes;
table(
  ['Mode', ...codes.map((c) => `**${c}**`)],
  travel.speeds.modes.map((m) => [m.name, ...codes.map((c) => m.hexesPerDayLeg[c] || '—')])
);
say('Overrides: ' + travel.speeds.overrides.map((o) =>
  `**${o.name}** — ${Object.entries(o.hexesPerDayLeg).map(([m, v]) => `${m} ${v}`).join(', ')}`).join('; ') + '.');
say();
say('## Night legs');
say();
table(
  ['Light', 'Night speed'],
  [
    ['None', 'No travel at all, even on a road'],
    ['Torch', '1 hex (2 on a road); spends one use'],
    ['Lantern', 'Half day speed, rounded up'],
    ['Owl’s Eye potion', 'As a lantern, for one round'],
  ]
);
say('A night leg triggers a second discovery roll with the monster band widened by 1.');
say('Trains run at night at full speed with a lantern fitted; ships sail at half speed with one rigged.');
say('Caves can only be entered with a lit torch or lantern.');
say();

/* ---------------------------------------------------------------- discovery */
say('## Discovery tables — d20, roll where the leg ends');
say();
say('One roll per movement leg, on the table for the hex you **stopped** in. A road');
say('or rail on the hex overrides its terrain. Persistent results are marked on the');
say('hex with a tile or figure.');
say();
table(
  ['Table', 'Bands'],
  discovery.tables.map((t) => [
    t.name,
    t.entries.map((e) => `${e.roll} ${e.result}`).join(' · '),
  ])
);
say('Monster element weights by table:');
say();
table(
  ['Table', 'Fire', 'Earth', 'Water', 'Air'],
  discovery.tables.map((t) => [
    t.name,
    t.elementWeights?.fire ?? 0, t.elementWeights?.earth ?? 0,
    t.elementWeights?.water ?? 0, t.elementWeights?.air ?? 0,
  ])
);

/* -------------------------------------------------------------- commodities */
say('## The market');
say();
say('Every Market phase, per commodity line in play: roll two red dice for demand, two');
say('blue for supply and one green for elasticity, add what the line remembers, and read');
say('the result on the swing ruler printed across the foot of the market board.');
say();
say('```');
say(pricing.formula.net);
say('```');
say();
table(
  ['Dice', 'Colour', 'Range', 'What it is'],
  pricing.dice.sets.map((d) => [`${d.count} d${d.faces}`, d.colour, `${d.range[0]}–${d.range[1]}`, d.name])
);
table(
  ['Green die', 'Elasticity', '', ''],
  pricing.elasticity.steps.map((e) => [
    `**${e.faces[0]}–${e.faces[e.faces.length - 1]}**`, `**${e.label}**`, e.name, e.means,
  ])
);
say('Halving rounds toward zero, so an inelastic season can shrink a swing away to');
say('nothing but can never turn it around.');
say();
say('### The swing ruler');
say();
table(
  ['Net', ...pricing.ruler.bins.map((b) => `**${b.label}**`)],
  [
    ['Bands', ...pricing.ruler.bins.map((b) => (b.move === 0 ? 'hold' : b.move > 0 ? `+${b.move}` : `\u2212${Math.abs(b.move)}`))],
    ['', ...pricing.ruler.bins.map((b) => b.name.toLowerCase())],
  ]
);
say(`The board sells no more of a commodity in a round than that round's supply roll,`);
say('first come first served in turn order. It will buy any quantity.');
say();
say('### What a market remembers');
say();
say(`Each line carries a tally of the board's own stock — up one cell per token sold to`);
say(`the board, down one per token bought off it — and a modifier from \u2212${Math.abs(pricing.memory.from)} to`);
say(`+${pricing.memory.to} that the tally moves. Every ${pricing.memory.tally.to} tokens the tally fills, which takes it`);
say('back to empty and steps the modifier one cell. Which way it steps is the');
say(`commodity's own model, and the model's mark is engraved in the corner of that`);
say(`commodity's token.`);
say();
table(
  ['Model', 'Memory', 'Tally', 'What it is'],
  pricing.models.map((m) => [
    priceModel(m.id),
    `${m.memory.from < 0 ? `\u2212${Math.abs(m.memory.from)}` : m.memory.from} to ${m.memory.to > 0 ? '+' : ''}${m.memory.to}`,
    m.tally.uses ? `${m.tally.dischargeStep > 0 ? '+' : '−'}1 when full` : '—',
    `**${m.line}** ${m.assigns}`,
  ])
);

/* ------------------------------------------------------------ worked markets */
/*
 * Three markets played out, one per model. The DICE are chosen — a worked
 * example shows the interesting case, not a random one — and every number
 * downstream of them is computed from data/pricing.json, so this section cannot
 * quietly stop being true when a ruler bin moves. That is the same bargain the
 * rest of the annex makes; it is just doing arithmetic rather than transcribing.
 */
const WORKED = [
  {
    title: 'A good harvest',
    commodity: 'grain',
    blurb: 'Bram has a farm and a surplus, and sells it into his own town three rounds running.',
    rounds: [
      { note: 'His first surplus.', sell: 3, red: [4, 3], blue: [5, 6], green: 2 },
      { note: 'A thin market — and he sells into it anyway.', sell: 3, red: [6, 5], blue: [3, 2], green: 4 },
      { note: 'And again.', sell: 4, red: [3, 3], blue: [4, 4], green: 1 },
      { note: 'Nobody sells. The memory bites.', red: [5, 4], blue: [4, 3], green: 3 },
      { note: 'A famine year, and the market has just about forgotten him.', red: [6, 6], blue: [2, 1], green: 4 },
    ],
  },
  {
    title: 'A run on gold',
    commodity: 'gold',
    blurb: 'Nobody trades a single ingot. A hype line does all of this on its own.',
    rounds: [
      { note: 'Gold firms.', red: [5, 6], blue: [2, 3], green: 2 },
      { note: 'And firms again. The run is building.', red: [4, 5], blue: [3, 3], green: 1 },
      { note: 'A roll that says nothing — but the hype carries it.', red: [3, 4], blue: [4, 4], green: 1 },
      { note: 'The turn.', red: [2, 2], blue: [6, 5], green: 4 },
      { note: 'And it runs the other way just as fast.', red: [3, 3], blue: [5, 4], green: 4 },
    ],
  },
  {
    title: 'The seam runs out',
    commodity: 'iron-ore',
    blurb: 'Ilsa opens a mine and ships everything she digs. The rolls are ordinary throughout.',
    rounds: [
      { note: 'She opens the mine.', sell: 4, red: [4, 4], blue: [4, 5], green: 1 },
      { note: 'Another four out of the ground.', sell: 4, red: [5, 3], blue: [3, 4], green: 2 },
      { note: 'And another four.', sell: 4, red: [4, 5], blue: [4, 4], green: 1 },
      { note: 'A bad roll — and look what it does not do.', sell: 3, red: [3, 4], blue: [5, 5], green: 1 },
      { note: 'Nobody mines at all this round.', red: [4, 3], blue: [4, 4], green: 2 },
    ],
  },
];

const BANDS = rules.market.priceBands;
const TALLY = pricing.memory.tally;
const CAPACITY = TALLY.to - TALLY.from + 1;
const clampTo = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
const towardZero = (n) => (n < 0 ? Math.ceil(n) : Math.floor(n));
const signOf = (n) => (n > 0 ? `+${n}` : n < 0 ? `\u2212${Math.abs(n)}` : '0');
const coin = (n) => `${n.toFixed(2)}${rules.currency.symbol}`;

/** One scenario, played. Returns the markdown rows and the closing line. */
function play(scene) {
  const c = commodities.commodities.find((x) => x.id === scene.commodity);
  const model = pricing.models.find((m) => m.id === c.pricing);
  let band = rules.market.startingBandIndex;
  let mem = pricing.memory.start;
  let tally = TALLY.start;
  let filled = false;
  const rows = [];

  for (const [i, r] of scene.rounds.entries()) {
    /* Actions phase: the trade happens at the price already on the board, and
       the tally walks — and discharges — in the hand of whoever traded. */
    let did = '—';
    if (r.sell) {
      const each = c.baseValue * BANDS[band] * (1 + rules.market.sellSpread);
      did = `sells **${r.sell}** at ${coin(each)} = **${coin(each * r.sell)}**`;
      const t = model.tally;
      if (t.uses && t.onSell) {
        let n = tally + t.onSell * r.sell;
        let steps = 0;
        while (n > TALLY.to) { n -= CAPACITY; steps += 1; }
        tally = Math.max(TALLY.from, n);
        if (steps) {
          filled = true;
          mem = clampTo(mem + steps * t.dischargeStep, model.memory.from, model.memory.to);
          did += ` · tally fills → memory **${signOf(mem)}**, tally ${tally}`;
        } else {
          did += ` · tally ${tally}`;
        }
      }
    }

    /* Market phase: roll, fix the price for next round, then update the memory. */
    const D = r.red[0] + r.red[1];
    const S = r.blue[0] + r.blue[1];
    const step = pricing.elasticity.steps.find((e) => e.faces.includes(r.green));
    const memAtRoll = mem;
    const net = towardZero((D - S + mem) * step.multiply);
    const bin = pricing.ruler.bins.find((b) => net >= b.from && net <= b.to);
    const was = band;
    band = clampTo(band + bin.move, 0, BANDS.length - 1);
    const moved = band - was;

    if (model.memory.followsPrice) {
      if (moved > 0) mem += 1;
      else if (moved < 0) mem -= 1;
      else if (model.memory.decayToZero === 'no-move') mem -= Math.sign(mem);
    } else if (model.tally.uses && model.memory.decayToZero === 'quiet-tally' && !filled) {
      mem -= Math.sign(mem);
    }
    filled = false;
    mem = clampTo(mem, model.memory.from, model.memory.to);

    rows.push([
      i + 1,
      did,
      `${D} − ${S}`,
      signOf(memAtRoll),
      step.label,
      net < 0 ? `\u2212${Math.abs(net)}` : String(net),
      bin.move === 0 ? 'hold' : signOf(bin.move),
      `**×${BANDS[band]}** (${coin(c.baseValue * BANDS[band])})`,
      signOf(mem),
      model.tally.uses ? String(tally) : '—',
    ]);
  }
  return { c, model, rows, band, mem };
}

say('## Three markets, played');
say();
say('One scenario per model, with the dice chosen to show what each one does. Everything');
say('after the dice is worked from the tables above rather than transcribed, so these');
say('cannot drift out of true. Trading happens in the **Actions** phase at the price');
say('already on the board; the Market phase then fixes the price for the round to come.');
say();

for (const scene of WORKED) {
  const { c, model, rows, band, mem } = play(scene);
  say(`### ${scene.title} — ${c.name} · ${priceModel(model.id)}`);
  say();
  say(`${scene.blurb} Base value ${c.baseValue}${rules.currency.symbol}; every token starts on ×${BANDS[rules.market.startingBandIndex]}, memory 0, tally 0.`);
  say();
  table(
    ['#', 'Actions phase', 'D − S', 'Mem', 'Green', 'Net', 'Bands', 'Price now', 'Mem after', 'Tally'],
    rows
  );
  say(`**After five rounds:** ×${BANDS[band]} — ${c.name} at ${coin(c.baseValue * BANDS[band])} a ${c.unit} — with the memory on ${signOf(mem)}. ${model.line}`);
  say();
}

/* -------------------------------------------------------------- commodities */
say('## Commodities');
say();
table(
  ['Commodity', 'Category', 'Bulk', 'Value', 'Prices by', 'Perishes', 'Tags'],
  commodities.commodities.map((c) => [
    c.name, c.category, c.bulk, c.baseValue, priceModel(c.pricing),
    c.perishRounds ? `${c.perishRounds} rounds` : '—', list(c.tags),
  ])
);

/* -------------------------------------------------------------------- tools */
say('## Tools');
say();
table(
  ['Tool', 'Made at', 'Craft', 'Hours', 'Value', 'Durability'],
  tools.tools.map((t) => [
    t.name, t.madeAt, io(t.craft?.inputs), t.craft?.effortHours, t.baseValue,
    t.baseDurability + (t.optional ? ' (optional)' : ''),
  ])
);

/* ---------------------------------------------------------------- buildings */
say('## Buildings');
say();
table(
  ['Building', 'Category', 'Tier', 'Cost', 'Points', 'Terrain'],
  buildings.buildings.map((b) => [
    b.name, b.category, b.tier, io(b.cost), b.buildPoints, list(b.terrain),
  ])
);

/* ------------------------------------------------------------------ peoples */
say('## Peoples');
say();
table(
  ['People', 'Die', 'Workers', 'Terrain comfort', 'Strength', 'Defence', 'Carries', 'Mana'],
  peoples.peoples.map((p) => [
    p.name, p.effortDie, p.startingWorkers, list(p.terrainComfort),
    p.strength?.base,
    p.defence?.base,
    `${(p.strength?.base ?? 0) * rules.carrying.kgPerStrength} kg`,
    p.manaStorage?.innate ? `${p.manaStorage.innate} innate` : 'talisman only',
  ])
);
say();
say('Carrying is not a separate number and has not been since strength swallowed');
say(`burden: a figure lifts strength × ${rules.carrying.kgPerStrength} ${rules.carrying.unit}, and the column above is that`);
say('sum rather than a value anybody chose.');
say('### Traits');
say();
table(
  ['People', 'Trait', 'Effect'],
  peoples.peoples.flatMap((p) => p.traits.map((t) => [p.name, t.name, t.effect]))
);
say('### Professions');
say();
table(
  ['Profession', 'Trained at', 'Coin', 'Hours', 'Bonus'],
  peoples.professions.map((p) => [
    p.name, p.building, p.trainCost?.coin, p.trainCost?.effortHours, p.bonus,
  ])
);

/* -------------------------------------------------------------------- items */
say('## Items');
say();
say('Mass is what the thing weighs. It counts against what the carrier can lift —');
say(`strength × ${rules.carrying.kgPerStrength} ${rules.carrying.unit}, printed on every character card — and it is not`);
say('bulk: bulk is a commodity\'s storage and shipping cost, and no item has one.');
say();
say(`No figure in the game shoulders more than ${Math.max(...peoples.peoples.map((p) => (p.strength?.base ?? 0) * rules.carrying.kgPerStrength), ...characters.characters.map((c) => c.strength * rules.carrying.kgPerStrength))} ${rules.carrying.unit} unaided, and`);
say('nothing walks a token for it: a load either fits under the printed limit or');
say('it does not.');
say();
for (const cls of items.classes) {
  const rows = items.items.filter((i) => i.class === cls.id);
  if (!rows.length) continue;
  say(`### ${cls.name}`);
  say();
  const extra = cls.id === 'talisman' ? ['Capacity'] : [];
  table(
    ['Item', 'Made at', 'Inputs', 'Hours', 'Value', 'Mass', ...extra, 'Effects'],
    rows.map((i) => [
      i.name + (i.cardCode ? ` (${i.cardCode})` : ''), i.madeAt, io(i.inputs), i.effortHours, i.baseValue,
      `${i.massKg} kg`,
      ...(cls.id === 'talisman' ? [i.manaCapacity] : []),
      (i.effects || []).join(' '),
    ])
  );
}

/* ---------------------------------------------------------------- transport */
say('## Transport modes');
say();
table(
  ['Mode', 'Tier', 'Capacity', 'Speed', 'Needs', 'Buy', 'Upkeep', 'Theft risk'],
  transport.modes.map((m) => [
    m.name, m.tier, m.capacity,
    m.speedOnRoad ? `${m.speed} (${m.speedOnRoad} on road)` : m.speed,
    m.requires === 'none' ? '—' : m.requires, m.buyCost || 'free', m.upkeep, '★'.repeat(m.theftRisk || 0) || '—',
  ])
);

/* ----------------------------------------------------------------- vehicles */
say('## Vehicle deck');
say();
say('**H** is the hull, **C** the bulk of its hold — the two boxes of a vehicle');
say('card\'s summary strip. A vehicle in play is dealt a player board of its own and');
say('run like a player who is not a person: the hull walks that board\'s health');
say('track, and the cargo and modifications lie in its four kit slots.');
say();
table(
  ['Code', 'Vehicle', 'Kind', 'Cargo', 'Hull', 'Quirk'],
  vehicles.vehicles.map((v) => [
    v.cardCode, v.name, v.mode, v.cargoCapacity, v.hull, v.quirk,
  ])
);

/* ----------------------------------------------------------------- monsters */
say('## Monster deck');
say();
say('S = slay (always allowed), E = enslave, B = befriend, D = domesticate.');
say('Slaying yields the mana; the other three trade mana away for a living asset.');
say();
table(
  ['Code', 'Monster', 'Element', 'Str', 'Def', 'Health', 'Mana', 'Ground', 'Options'],
  monsters.monsters.map((m) => [
    m.cardCode, m.name + (m.unique ? ' *(unique)*' : ''), element(m.element), m.strength, m.defence, m.health, m.manaYield,
    list(m.terrains),
    'S' + (m.options.enslave ? ' E' : '') + (m.options.befriend ? ' B' : '') + (m.options.domesticate ? ' D' : ''),
  ])
);
say();
say(`In a fight: ${rules.conflict.attack.rule} ${rules.conflict.attack.formula}, clamped to`);
say(`${rules.conflict.attack.clamp[0]}+ and ${rules.conflict.attack.clamp[1]}+. Strength is what a thing swings with, defence is what makes`);
say('you miss — a stone boar barely swings and still turns a sword.');

/* --------------------------------------------------------------- characters */
say('## Character deck');
say();
say('The six boxes of the summary strip across the top of every character card,');
say('in the order they are printed in — and the same letters the player board');
say('calls its tracks, so setting up is reading across the strip and placing');
say('tokens left to right.');
say();
table(
  ['Code', 'Character', 'People', 'Calling', 'H', 'S', 'D', 'M', rules.currency.symbol, 'KG', 'Traits'],
  characters.characters.map((c) => [
    c.cardCode, c.name, c.people, c.calling,
    c.health, c.strength, c.defence, c.manaCapacity || '—', c.startingGold,
    c.strength * rules.carrying.kgPerStrength,
    (c.traits || []).join(' '),
  ])
);

/* ------------------------------------------------------------------- quests */
say('## Quest deck');
say();
table(
  ['Code', 'Quest', 'Type', 'Cx', 'Task'],
  quests.quests.map((q) => [
    q.cardCode, q.name, q.type, q.complexity,
    q.task || `${q.stages.length} stages: ${q.stages.map((s) => s.name).join(' → ')}`,
  ])
);

/* ------------------------------------------------------ elements and arcana */
say('## The elements');
say();
say('Four elements, four marks. The mark is data - one path per element in');
say('`data/arcana.json` - so a card, a chit, this table and the explorer all say');
say('fire the same way. `tools/build-icons.mjs` draws them.');
say();
table(
  ['Mark', 'Element', 'Ink', 'At home'],
  arcana.elements.map((e) => [elementMark(e.id), `**${e.name}**`, e.ink, e.summary])
);

say('## Spells');
say();
table(
  ['Code', 'Spell', 'Element', 'Mana', 'Effect'],
  arcana.spells.map((s) => [s.cardCode, s.name, element(s.element), s.cost, s.effect])
);

say('## Enchantments');
say();
say(arcana.enchantments.$comment.split('.')[0] + '.');
say();
table(
  ['Code', 'Enchantment', 'Element', 'Mana', 'Bound to', 'Effect'],
  arcana.enchantments.cards.map((e) => [e.cardCode, e.name, element(e.element), e.cost, e.boundTo, e.effect])
);

/* ----------------------------------------------------------- modifications */
say('## Modification deck');
say();
say('Fittings and enchantments bolted onto a vehicle. They share the vehicle\'s');
say(`slots — ${modifications.slots.base} on most, and at most ${modifications.slots.enchantmentLimit} enchantment whatever the count — so a`);
say('shipwright and a hedge-witch are competing for the same hull.');
say();
table(
  ['Code', 'Modification', 'Class', 'Fits', 'Cost', 'Effect'],
  modifications.modifications.map((m) => [
    m.cardCode, m.name, m.class, list(m.fits),
    m.manaCost ? `${m.manaCost} ${m.element} mana` : io(m.inputs),
    m.effect,
  ])
);

/* -------------------------------------------------------------------- events */
say('## Event deck');
say();
table(
  ['Card', 'Category', 'Scope', 'Copies'],
  events.cards.map((c) => [c.name, c.category, c.scope, c.copies])
);
say(`${events.deck.totalCards} cards. ${events.deck.when}`);
say();

const out = lines.join('\n');
if (checkOnly) {
  let current = '';
  try { current = readFileSync(OUT, 'utf8'); } catch { /* absent counts as stale */ }
  if (current !== out) {
    console.error('docs/design/14-annex.md is stale. Run: node tools/build-annex.mjs');
    process.exit(1);
  }
  console.log('docs/design/14-annex.md is up to date');
} else {
  writeFileSync(OUT, out, 'utf8');
  console.log(`wrote docs/design/14-annex.md (${(out.length / 1024).toFixed(1)} kB)`);
}
